// Beispieldaten zum Ausprobieren der App.

export const DEMO_BOOKS = [
  { title: 'Der Hobbit', authors: ['J.R.R. Tolkien'], year: 1937, pages: 380, format: 'Taschenbuch', location: 'Wohnzimmer, Regal 1',
    subjects: ['fantasy', 'adventure', 'dragons', 'dwarves', 'quests'], status: 'read', rating: 5, finishedAt: '2026-01-18',
    review: 'Gemütlich, witzig und zeitlos. Bilbo ist der beste unfreiwillige Held.' },
  { title: 'Der Name des Windes', authors: ['Patrick Rothfuss'], year: 2007, pages: 860, format: 'Hardcover', location: 'Wohnzimmer, Regal 1',
    subjects: ['fantasy', 'magic', 'coming of age', 'music', 'epic fantasy'], status: 'read', rating: 5, finishedAt: '2026-03-02',
    review: 'Wunderschöne Sprache, ich wollte nicht, dass es endet.' },
  { title: 'Die unendliche Geschichte', authors: ['Michael Ende'], year: 1979, pages: 480, format: 'Hardcover', location: 'Wohnzimmer, Regal 1',
    subjects: ['fantasy', 'adventure', 'imaginary places', 'books and reading'], status: 'read', rating: 4, finishedAt: '2025-11-20',
    review: 'Als Erwachsene:r nochmal ganz anders gelesen.' },
  { title: '1984', authors: ['George Orwell'], year: 1949, pages: 328, format: 'Taschenbuch', location: 'Arbeitszimmer',
    subjects: ['dystopias', 'science fiction', 'totalitarianism', 'political fiction'], status: 'read', rating: 4, finishedAt: '2026-05-14',
    review: 'Bedrückend aktuell.' },
  { title: 'Der Schwarm', authors: ['Frank Schätzing'], year: 2004, pages: 1000, format: 'Taschenbuch', location: 'Keller, Kiste 2',
    subjects: ['thrillers', 'science fiction', 'ocean', 'environmental fiction'], status: 'read', rating: 2, finishedAt: '2026-07-30',
    review: 'Spannende Idee, aber 500 Seiten zu lang.' },
  { title: 'Stolz und Vorurteil', authors: ['Jane Austen'], year: 1813, pages: 432, format: 'Taschenbuch', location: 'Arbeitszimmer',
    subjects: ['classics', 'love stories', 'social classes', 'england'], status: 'read', rating: 3, finishedAt: '2026-08-22',
    review: 'Charmant, aber nicht ganz meins.' },
  { title: 'Kinder des Nebels', authors: ['Brandon Sanderson'], year: 2006, pages: 800, format: 'Paperback', location: 'Wohnzimmer, Regal 2',
    subjects: ['fantasy', 'magic', 'heists', 'epic fantasy'], status: 'unread' },
  { title: 'Die Physiker', authors: ['Friedrich Dürrenmatt'], year: 1962, pages: 96, format: 'Taschenbuch', location: 'Arbeitszimmer',
    subjects: ['drama', 'classics', 'science', 'ethics'], status: 'unread' },
  { title: 'Der Report der Magd', authors: ['Margaret Atwood'], year: 1985, pages: 400, format: 'Taschenbuch', location: 'Wohnzimmer, Regal 2',
    subjects: ['dystopias', 'feminism', 'political fiction', 'science fiction'], status: 'unread', lentTo: 'Anna' },
  { title: 'Das Parfum', authors: ['Patrick Süskind'], year: 1985, pages: 320, format: 'Taschenbuch', location: 'Nachttisch',
    subjects: ['historical fiction', 'crime', 'france', 'classics'], status: 'reading', startedAt: '2026-09-15' },
  { title: 'Die Stadt der träumenden Bücher', authors: ['Walter Moers'], year: 2004, pages: 480,
    subjects: ['fantasy', 'books and reading', 'humorous fiction', 'imaginary places'], status: 'wishlist' },
];
